const productos = [
    // Hortalizas
    { nombre: "Acelga Tallo Naranjo", img: "acelga_tallo_naranjo.png", categoria: "hortalizas" },
    { nombre: "Achicoria", img: "achicoria.jpg", categoria: "hortalizas" },
    { nombre: "Ají Cacho", img: "aji_cacho.jpg", categoria: "hortalizas" },
    { nombre: "Ají Cristal", img: "aji_cristal.jpeg", categoria: "hortalizas" },
    { nombre: "Ají Habanero", img: "ají_habanero.png", categoria: "hortalizas" },
    { nombre: "Amaranto", img: "amaranto.jpg", categoria: "hortalizas" },
    { nombre: "Apio", img: "apio.jpg", categoria: "hortalizas" },
    { nombre: "Berenjena", img: "berenjena.png", categoria: "hortalizas" },
    { nombre: "Berro", img: "berro.jpg", categoria: "hortalizas" },
    { nombre: "Brócoli", img: "brocoli.jpg", categoria: "hortalizas" },
    { nombre: "Buselas", img: "buselas.png", categoria: "hortalizas" },
    { nombre: "Cebolla Morada", img: "cebolla_morada.jpg", categoria: "hortalizas" },
    { nombre: "Cebolla Texas", img: "cebolla_texas.png", categoria: "hortalizas" },
    { nombre: "Col China", img: "col_china.jpg", categoria: "hortalizas" },
    { nombre: "Coliflor", img: "coliflor.jpg", categoria: "hortalizas" },
    { nombre: "Coliflor Romanesco", img: "coliflor_romanesco.gif", categoria: "hortalizas" },
    { nombre: "Kale 2", img: "kale_2.webp", categoria: "hortalizas" },
    { nombre: "Kale Crespo", img: "kale_crespo.png", categoria: "hortalizas" },
    { nombre: "Kale Rizado", img: "kale_rizado.jpg", categoria: "hortalizas" },
    { nombre: "Kale Toscano", img: "kale_toscano.jpg", categoria: "hortalizas" },
    { nombre: "Lechuga Catalana", img: "lechuga_catalogna_roja.png", categoria: "hortalizas" },
    { nombre: "Lechuga Lollo Rosa", img: "lechuga_lollo_rosa.jpg", categoria: "hortalizas" },
    { nombre: "Lechuga Lunanera", img: "lechuga_lunanera.png", categoria: "hortalizas" },
    { nombre: "Lechuga Matrioska", img: "lechuga_matrioska.jpg", categoria: "hortalizas" },
    { nombre: "Lechuga Red Salad Bowl", img: "lechuga_red_salad_bowl.png", categoria: "hortalizas" },
    { nombre: "Melón Calameño", img: "melon_calameno.jpg", categoria: "hortalizas" },
    { nombre: "Melón Tuna", img: "melon_tuna.png", categoria: "hortalizas" },
    { nombre: "Mizuna Roja", img: "mizuna_roja.jpg", categoria: "hortalizas" },
    { nombre: "Mizuna Verde", img: "mizuna_verde.jpg", categoria: "hortalizas" },
    { nombre: "Mostaza", img: "mostaza.png", categoria: "hortalizas" },
    { nombre: "Nabo", img: "nabo.jpg", categoria: "hortalizas" },
    { nombre: "Okra", img: "okra.jpg", categoria: "hortalizas" },
    { nombre: "Pak Choi Rojo", img: "pak_choi_rojo.png", categoria: "hortalizas" },
    { nombre: "Pak Choi Verde", img: "pak_choi_verde.png", categoria: "hortalizas" },
    { nombre: "Perejil Crespo", img: "perejil_crespo.jpg", categoria: "hortalizas" },
    { nombre: "Pimentón Rojo", img: "pimenton_rojo.jpg", categoria: "hortalizas" },
    { nombre: "Pimiento Amarillo", img: "pimiento_amarillo.jpg", categoria: "hortalizas" },
    { nombre: "Puerros", img: "puerros.jpeg", categoria: "hortalizas" },
    { nombre: "Rúcula", img: "rucula.jpg", categoria: "hortalizas" },
    { nombre: "Sandía Antonia", img: "sandia_antonia.png", categoria: "hortalizas" },
    { nombre: "Sandía Klondike", img: "sandia_klondike.png", categoria: "hortalizas" },
    { nombre: "Tatsoi", img: "tatsoi.png", categoria: "hortalizas" },
    { nombre: "Tomate Amarillo", img: "tomate_amarillo.png", categoria: "hortalizas" },
    { nombre: "Tomate Cal Ace", img: "tomate_cal_ace.jpg", categoria: "hortalizas" },
    { nombre: "Tomate Rosado", img: "tomate_rosado.jpg", categoria: "hortalizas" },
    { nombre: "Zapallo Butternut", img: "zapallo_butternut.png", categoria: "hortalizas" },
    { nombre: "Zapallo It. Amarillo", img: "zapallo_italiano_amarillo.png", categoria: "hortalizas" },
    { nombre: "Zapallo It. Bola8", img: "zapallo_italiano_bola8.png", categoria: "hortalizas" },
    { nombre: "Zapallo It. Gris", img: "zapallo_italiano_gris.jpg", categoria: "hortalizas" },
    // Flores
    { nombre: "Alegría del hogar", img: "foto_flores/alegria_del_hogar.jpg", categoria: "flores" },
    { nombre: "Amapola Doble", img: "foto_flores/amapolas_doble.jpg", categoria: "flores" },
    { nombre: "Borraja", img: "foto_flores/borraja.jpg", categoria: "flores" },
    { nombre: "Cactus y Suculentas", img: "foto_flores/cactus_y_suculentas.png", categoria: "flores" },
    { nombre: "Caléndula", img: "foto_flores/calendulas.png", categoria: "flores" },
    { nombre: "Cartuchos", img: "foto_flores/cartuchos.png", categoria: "flores" },
    { nombre: "Celosía Cresta", img: "foto_flores/celosia_cresta_de_gallo.jpg", categoria: "flores" },
    { nombre: "Celosía Plumosa", img: "foto_flores/celosia_plumosa.jpg", categoria: "flores" },
    { nombre: "Clavel Gigante", img: "foto_flores/clavel_gigante.jpg", categoria: "flores" },
    { nombre: "Clavelina China", img: "foto_flores/clavelina_china.jpg", categoria: "flores" },
    { nombre: "Clavelina Japonesa", img: "foto_flores/clavelina_japonesa.jpg", categoria: "flores" },
    { nombre: "Clavel Lanudo", img: "foto_flores/clavel_lanudo.jpg", categoria: "flores" },
    { nombre: "Clavelón Enano", img: "foto_flores/clavelon_enano.jpg", categoria: "flores" },
    { nombre: "Cosmos Sensación", img: "foto_flores/cosmos_sensacion.jpg", categoria: "flores" },
    { nombre: "Crisantemos", img: "foto_flores/crisantemos_variados.jpg", categoria: "flores" },
    { nombre: "Dalia Cactus", img: "foto_flores/dalia_cactus.jpg", categoria: "flores" },
    { nombre: "Dalia Enana", img: "foto_flores/dalia_enana.jpg", categoria: "flores" },
    { nombre: "Gazanias", img: "foto_flores/gazanias_mixtas.jpg", categoria: "flores" },
    { nombre: "Girasol Amarillo", img: "foto_flores/girasol_amarillo.jpg", categoria: "flores" },
    { nombre: "Ilusión", img: "foto_flores/ilusion_paniculata.jpg", categoria: "flores" },
    { nombre: "Malva Mixta", img: "foto_flores/malva_mixta.png", categoria: "flores" },
    { nombre: "Manzanilla", img: "foto_flores/manzanilla.jpg", categoria: "flores" },
    { nombre: "Margarita Africana", img: "foto_flores/margarita_africana.jpg", categoria: "flores" },
    { nombre: "Petunia Colorama", img: "foto_flores/petunia_colorama.png", categoria: "flores" },
    { nombre: "Reina Luisa Americana", img: "foto_flores/reina_luisa_americana.jpg", categoria: "flores" },
    { nombre: "Reina Luisa Doble", img: "foto_flores/reina_luisa_doble.jpg", categoria: "flores" },
    { nombre: "Reina Luisa Matsumoto", img: "foto_flores/reina_luisa_matsumoto.jpg", categoria: "flores" },
    { nombre: "Suspiros", img: "foto_flores/suspiros.png", categoria: "flores" },
    // Porotos
    { nombre: "Alcayota", img: "foto_porotos/alcayota.jpg", categoria: "Legumbres y varios" },
    { nombre: "Arveja de Mata", img: "foto_porotos/arveja_de_mata.jpg", categoria: "Legumbres y varios" },
    { nombre: "Arveja Sin Hila", img: "foto_porotos/arveja_sin-hila.jpg", categoria: "Legumbres y varios" },
    { nombre: "Arvejón de Guía", img: "foto_porotos/arvejon_de_guia.jpg", categoria: "Legumbres y varios" },
    { nombre: "Arvejón Mata", img: "foto_porotos/arvejon_mata.jpg", categoria: "Legumbres y varios" },
    { nombre: "Ballica", img: "foto_porotos/ballica.jpg", categoria: "Legumbres y varios" },
    { nombre: "Cilantro Moggiano", img: "foto_porotos/cilantro_moggiano.jpg", categoria: "Legumbres y varios" },
    { nombre: "Cilantro Santo", img: "foto_porotos/cilantro_santo.jpg", categoria: "Legumbres y varios" },
    { nombre: "Habas Agua Dulce", img: "foto_porotos/habas_agua_dulce.jpg", categoria: "Legumbres y varios" },
    { nombre: "Habas Verdes", img: "foto_porotos/habas_verdes.png", categoria: "Legumbres y varios" },
    { nombre: "Maíz 12 Hileras", img: "foto_porotos/maiz_12_hileras.jpg", categoria: "Legumbres y varios" },
    { nombre: "Maíz Dulce", img: "foto_porotos/maiz_dulce.jpg", categoria: "Legumbres y varios" },
    { nombre: "Poroto Araucano", img: "foto_porotos/poroto_araucano.jpg", categoria: "Legumbres y varios" },
    { nombre: "Poroto Brio", img: "foto_porotos/poroto_brio.jpg", categoria: "Legumbres y varios" },
    { nombre: "Poroto Magnum", img: "foto_porotos/poroto_magnum.jpg", categoria: "Legumbres y varios" },
    { nombre: "Poroto Manteca", img: "foto_porotos/poroto_manteca.jpg", categoria: "Legumbres y varios" },
    { nombre: "Poroto Pallares", img: "foto_porotos/poroto_pallares.jpg", categoria: "Legumbres y varios" },
    { nombre: "Poroto Rubí", img: "foto_porotos/poroto_rubi.jpg", categoria: "Legumbres y varios" },
    { nombre: "Poroto Señorita", img: "foto_porotos/poroto_senorita.jpg", categoria: "Legumbres y varios" },
    { nombre: "Poroto Sofía", img: "foto_porotos/poroto_sofia.jpg", categoria: "Legumbres y varios" },
    // Semillas en Bolsa
    { nombre: "Acelga mix", img: "foto_bolsas_con_semillas_de_hortalizas/acelga_mix.jpg", categoria: "bolsas" },
    { nombre: "Albahaca Morada", img: "foto_bolsas_con_semillas_de_hortalizas/albahaca-morada.jpg", categoria: "bolsas" },
    { nombre: "Alcaparra", img: "foto_bolsas_con_semillas_de_hortalizas/alcaparra.webp", categoria: "bolsas" },
    { nombre: "Betarraga", img: "foto_bolsas_con_semillas_de_hortalizas/betarraga.webp", categoria: "bolsas" },
    { nombre: "Calabaza Mate", img: "foto_bolsas_con_semillas_de_hortalizas/calabaza_mate.jpg", categoria: "bolsas" },
    { nombre: "Ciboulette Fino", img: "foto_bolsas_con_semillas_de_hortalizas/ciboulette_fino.webp", categoria: "bolsas" },
    { nombre: "Hinojo", img: "foto_bolsas_con_semillas_de_hortalizas/hinojo.jpg", categoria: "bolsas" },
    { nombre: "Lechuga Batavia", img: "foto_bolsas_con_semillas_de_hortalizas/lechuga_batavia.png", categoria: "bolsas" },
    { nombre: "Lechuga Crespa", img: "foto_bolsas_con_semillas_de_hortalizas/lechuga_crespa_verde.jpg", categoria: "bolsas" },
    { nombre: "Lechuga Gallega de verano", img: "foto_bolsas_con_semillas_de_hortalizas/lechuga_gallega_de_verano.png", categoria: "bolsas" },
    { nombre: "Lechuga Maravilla", img: "foto_bolsas_con_semillas_de_hortalizas/lechuga_maravilla_de_verano.jpg", categoria: "bolsas" },
    { nombre: "Lechuga Reina Mayo", img: "foto_bolsas_con_semillas_de_hortalizas/lechuga_reina_de_mayo.jpg", categoria: "bolsas" },
    { nombre: "Mastuerzo", img: "foto_bolsas_con_semillas_de_hortalizas/mastuerzo.jpg", categoria: "bolsas" },
    { nombre: "Pepino Alaska", img: "foto_bolsas_con_semillas_de_hortalizas/pepino_alaska.webp", categoria: "bolsas" },
    { nombre: "Pepino Ensalada", img: "foto_bolsas_con_semillas_de_hortalizas/pepino_ensalada.webp", categoria: "bolsas" },
    { nombre: "Perejil Liso", img: "foto_bolsas_con_semillas_de_hortalizas/perejil_liso.png", categoria: "bolsas" },
    { nombre: "Rabanitos", img: "foto_bolsas_con_semillas_de_hortalizas/rabanitos.webp", categoria: "bolsas" },
    { nombre: "Repollo Morado", img: "foto_bolsas_con_semillas_de_hortalizas/repollo_morado.jpg", categoria: "bolsas" },
    { nombre: "Repollo Verde", img: "foto_bolsas_con_semillas_de_hortalizas/repollo_verde.jpg", categoria: "bolsas" },
    { nombre: "Tomillo", img: "foto_bolsas_con_semillas_de_hortalizas/tomillo_chascudo.png", categoria: "bolsas" },
    { nombre: "Zanahoria", img: "foto_bolsas_con_semillas_de_hortalizas/zanahoria.webp", categoria: "bolsas" },
    { nombre: "Zanahoria Redonda", img: "foto_bolsas_con_semillas_de_hortalizas/zanahoria_redonda.jpg", categoria: "bolsas" },
    { nombre: "Zapallo Camote", img: "foto_bolsas_con_semillas_de_hortalizas/zapallo_camote.png", categoria: "bolsas" },
    { nombre: "Zapallo Halloween", img: "foto_bolsas_con_semillas_de_hortalizas/zapallo_halloween.jpg", categoria: "bolsas" }
];
