const productos = [
    // Hortalizas
    { nombre: "Acelga Tallo Naranjo", img: "acelga_tallo_naranjo.png" },
    { nombre: "Achicoria", img: "achicoria.jpg" },
    { nombre: "Ají Cacho", img: "aji_cacho.jpg" },
    { nombre: "Ají Cristal", img: "aji_cristal.jpeg" },
    { nombre: "Ají Habanero", img: "ají_habanero.png" },
    { nombre: "Amaranto", img: "amaranto.jpg" },
    { nombre: "Apio", img: "apio.jpg" },
    { nombre: "Berenjena", img: "berenjena.png" },
    { nombre: "Berro", img: "berro.jpg" },
    { nombre: "Brócoli", img: "brocoli.jpg" },
    { nombre: "Buselas", img: "buselas.png" },
    { nombre: "Cebolla Morada", img: "cebolla_morada.jpg" },
    { nombre: "Cebolla Red", img: "cebolla_red.jpg" },
    { nombre: "Cebolla Texas", img: "cebolla_texas.png" },
    { nombre: "Col China", img: "col_china.jpg" },
    { nombre: "Coliflor", img: "coliflor.jpg" },
    { nombre: "Coliflor Romanesco", img: "coliflor_romanesco.gif" },
    { nombre: "Kale 2", img: "kale_2.webp" },
    { nombre: "Kale Crespo", img: "kale_crespo.png" },
    { nombre: "Kale Rizado", img: "kale_rizado.jpg" },
    { nombre: "Kale Toscano", img: "kale_toscano.jpg" },
    { nombre: "Lechuga Catalana", img: "lechuga_catalogna_roja.png" },
    { nombre: "Lechuga Lollo Rosa", img: "lechuga_lollo_rosa.jpg" },
    { nombre: "Lechuga Lunanera", img: "lechuga_lunanera.png" },
    { nombre: "Lechuga Matrioska", img: "lechuga_matrioska.jpg" },
    { nombre: "Lechuga Red Salad Bowl", img: "lechuga_red_salad_bowl.png" },
    { nombre: "Melón Calameño", img: "melon_calameno.jpg" },
    { nombre: "Melón Tuna", img: "melon_tuna.png" },
    { nombre: "Mizuna Roja", img: "mizuna_roja.jpg" },
    { nombre: "Mizuna Verde", img: "mizuna_verde.jpg" },
    { nombre: "Mostaza", img: "mostaza.png" },
    { nombre: "Nabo", img: "nabo.jpg" },
    { nombre: "Okra", img: "okra.jpg" },
    { nombre: "Pak Choi Rojo", img: "pak_choi_rojo.png" },
    { nombre: "Pak Choi Verde", img: "pak_choi_verde.png" },
    { nombre: "Perejil Crespo", img: "perejil_crespo.jpg" },
    { nombre: "Pimentón Rojo", img: "pimenton_rojo.jpg" },
    { nombre: "Pimiento Amarillo", img: "pimiento_amarillo.jpg" },
    { nombre: "Puerros", img: "puerros.jpeg" },
    { nombre: "Rúcula", img: "rucula.jpg" },
    { nombre: "Sandía Antonia", img: "sandia_antonia.png" },
    { nombre: "Sandía Klondike", img: "sandia_klondike.png" },
    { nombre: "Tatsoi", img: "tatsoi.png" },
    { nombre: "Tomate Amarillo", img: "tomate_amarillo.png" },
    { nombre: "Tomate Cal Ace", img: "tomate_cal_ace.jpg" },
    { nombre: "Tomate Rosado", img: "tomate_rosado.jpg" },
    { nombre: "Zapallo Butternut", img: "zapallo_butternut.png" },
    { nombre: "Zapallo It. Amarillo", img: "zapallo_italiano_amarillo.png" },
    { nombre: "Zapallo It. Bola8", img: "zapallo_italiano_bola8.png" },
    { nombre: "Zapallo It. Gris", img: "zapallo_italiano_gris.jpg" },
    // Flores
    { nombre: "Alegría del hogar", img: "foto_flores/alegria.jpg" },
    { nombre: "Amapola Doble", img: "foto_flores/amapolas_doble.jpg" },
    { nombre: "Borraja", img: "foto_flores/borraja.jpg" },
    { nombre: "Cactus y Suculentas", img: "foto_flores/cactus_y_suculentas.png" },
    { nombre: "Caléndula", img: "foto_flores/calendulas.png" },
    { nombre: "Cartuchos", img: "foto_flores/cartuchos.png" },
    { nombre: "Celosía Cresta", img: "foto_flores/celosia_cresta_de_gallo.jpg" },
    { nombre: "Celosía Plumosa", img: "foto_flores/celosia_plumosa.jpg" },
    { nombre: "Clavel Gigante", img: "foto_flores/clavel_gigante.jpg" },
    { nombre: "Clavelina China", img: "foto_flores/clavelina_china.jpg" },
    { nombre: "Clavelina Japonesa", img: "foto_flores/clavelina_japonesa.jpg" },
    { nombre: "Clavel Lanudo", img: "foto_flores/clavel_lanudo.jpg" },
    { nombre: "Clavelón Enano", img: "foto_flores/clavelon_enano.jpg" },
    { nombre: "Cosmos Sensación", img: "foto_flores/cosmos_sensacion.jpg" },
    { nombre: "Crisantemos", img: "foto_flores/crisantemos_variados.jpg" },
    { nombre: "Dalia Cactus", img: "foto_flores/dalia_cactus.jpg" },
    { nombre: "Dalia Enana", img: "foto_flores/dalia_enana.jpg" },
    { nombre: "Gazanias", img: "foto_flores/gazanias_mixtas.jpg" },
    { nombre: "Girasol Amarillo", img: "foto_flores/girasol_amarillo.jpg" },
    { nombre: "Ilusión", img: "foto_flores/ilusion_paniculata.jpg" },
    { nombre: "Malva Mixta", img: "foto_flores/malva_mixta.png" },
    { nombre: "Manzanilla", img: "foto_flores/manzanilla.jpg" },
    { nombre: "Margarita Africana", img: "foto_flores/margarita_africana.jpg" },
    { nombre: "Petunia Colorama", img: "foto_flores/petunia_colorama.png" },
    { nombre: "Reina Luisa Americana", img: "foto_flores/reina_luisa_americana.jpg" },
    { nombre: "Reina Luisa Doble", img: "foto_flores/reina_luisa_doble.jpg" },
    { nombre: "Reina Luisa Matsumoto", img: "foto_flores/reina_luisa_matsumoto.jpg" },
    { nombre: "Suspiros", img: "foto_flores/suspiros.png" },
    // Porotos
    { nombre: "Alcayota", img: "foto_porotos/alcayota.jpg" },
    { nombre: "Arveja de Mata", img: "foto_porotos/arveja_de_mata.jpg" },
    { nombre: "Arveja Sin Hila", img: "foto_porotos/arveja_sin-hila.jpg" },
    { nombre: "Arvejón de Guía", img: "foto_porotos/arvejon_de_guia.jpg" },
    { nombre: "Arvejón Mata", img: "foto_porotos/arvejon_mata.jpg" },
    { nombre: "Ballica", img: "foto_porotos/ballica.jpg" },
    { nombre: "Cilantro Moggiano", img: "foto_porotos/cilantro_moggiano.jpg" },
    { nombre: "Cilantro Santo", img: "foto_porotos/cilantro_santo.jpg" },
    { nombre: "Habas Agua Dulce", img: "foto_porotos/habas_agua_dulce.jpg" },
    { nombre: "Habas Verdes", img: "foto_porotos/habas_verdes.png" },
    { nombre: "Maíz 12 Hileras", img: "foto_porotos/maiz_12_hileras.jpg" },
    { nombre: "Maíz Dulce", img: "foto_porotos/maiz_dulce.jpg" },
    { nombre: "Poroto Araucano", img: "foto_porotos/poroto_araucano.jpg" },
    { nombre: "Poroto Brio", img: "foto_porotos/poroto_brio.jpg" },
    { nombre: "Poroto Magnum", img: "foto_porotos/poroto_magnum.jpg" },
    { nombre: "Poroto Manteca", img: "foto_porotos/poroto_manteca.jpg" },
    { nombre: "Poroto Pallares", img: "foto_porotos/poroto_pallares.jpg" },
    { nombre: "Poroto Rubí", img: "foto_porotos/poroto_rubi.jpg" },
    { nombre: "Poroto Señorita", img: "foto_porotos/poroto_senorita.jpg" },
    { nombre: "Poroto Sofía", img: "foto_porotos/poroto_sofia.jpg" },
    // Semillas en Bolsa
    { nombre: "Albahaca Morada", img: "img/foto_bolsas_con_semillas_de_hortalizas/albahaca-morada.jpg" },
    { nombre: "Alcaparra", img: "img/foto_bolsas_con_semillas_de_hortalizas/alcaparra.webp" },
    { nombre: "Betarraga", img: "img/foto_bolsas_con_semillas_de_hortalizas/betarraga.webp" },
    { nombre: "Calabaza Mate", img: "img/foto_bolsas_con_semillas_de_hortalizas/calabaza_mate.jpg" },
    { nombre: "Ciboulette Fino", img: "img/foto_bolsas_con_semillas_de_hortalizas/ciboulette_fino.webp" },
    { nombre: "Hinojo", img: "img/foto_bolsas_con_semillas_de_hortalizas/hinojo.jpg" },
    { nombre: "Lechuga Batavia", img: "img/foto_bolsas_con_semillas_de_hortalizas/lechuga_batavia.png" },
    { nombre: "Lechuga Crespa", img: "img/foto_bolsas_con_semillas_de_hortalizas/lechuga_crespa_verde.jpg" },
    { nombre: "Lechuga Maravilla", img: "img/foto_bolsas_con_semillas_de_hortalizas/lechuga_maravilla_de_verano.jpg" },
    { nombre: "Lechuga Reina Mayo", img: "img/foto_bolsas_con_semillas_de_hortalizas/lechuga_reina_de_mayo.jpg" },
    { nombre: "Mastuerzo", img: "img/foto_bolsas_con_semillas_de_hortalizas/mastuerzo.jpg" },
    { nombre: "Pepino Alaska", img: "img/foto_bolsas_con_semillas_de_hortalizas/pepino_alaska.webp" },
    { nombre: "Pepino Ensalada", img: "img/foto_bolsas_con_semillas_de_hortalizas/pepino_ensalada.webp" },
    { nombre: "Perejil Liso", img: "img/foto_bolsas_con_semillas_de_hortalizas/perejil_liso.png" },
    { nombre: "Rabanitos", img: "img/foto_bolsas_con_semillas_de_hortalizas/rabanitos.webp" },
    { nombre: "Repollo Morado", img: "img/foto_bolsas_con_semillas_de_hortalizas/repollo_morado.jpg" },
    { nombre: "Repollo Verde", img: "img/foto_bolsas_con_semillas_de_hortalizas/repollo_verde.jpg" },
    { nombre: "Tomillo", img: "img/foto_bolsas_con_semillas_de_hortalizas/tomillo_chascudo.png" },
    { nombre: "Zanahoria", img: "img/foto_bolsas_con_semillas_de_hortalizas/zanahoria.webp" },
    { nombre: "Zanahoria Redonda", img: "img/foto_bolsas_con_semillas_de_hortalizas/zanahoria_redonda.jpg" },
    { nombre: "Zapallo Camote", img: "img/foto_bolsas_con_semillas_de_hortalizas/zapallo_camote.png" },
    { nombre: "Zapallo Halloween", img: "img/foto_bolsas_con_semillas_de_hortalizas/zapallo_halloween.jpg" }
];
